# Generated by Django 5.2.2 on 2025-07-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_email_customer_tax_number"),
        ("orders", "0001_initial"),
        ("organizations", "0003_alter_plan_max_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Branches where this order is available.",
                related_name="order_branches",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer who placed this order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_category_discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_category_discount_price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge_price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Planned delivery date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="inward_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the order was received.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The main organization this order belongs to. Optional if shared across branches.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_price",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloth_name", models.CharField(max_length=100)),
                (
                    "cloth_arabic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cloth_description", models.TextField(blank=True, null=True)),
                (
                    "cloth_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("service_description", models.TextField(blank=True, null=True)),
                (
                    "service_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("handling_name", models.CharField(max_length=100)),
                ("handling_description", models.TextField(blank=True, null=True)),
                (
                    "handling_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("delivery_name", models.CharField(max_length=100)),
                ("delivery_description", models.TextField(blank=True, null=True)),
                (
                    "delivery_charge_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "delivery_charge_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "customer_category_name",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "customer_category_discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "customer_category_discount_price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rate_per_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "area_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0.0, max_digits=10
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "vat_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "vat_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0.0, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
