# Generated by Django 5.2.2 on 2025-07-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_user_order_branches_order_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer_category_discount_percent",
            new_name="discount_percent",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer_category_discount_price",
            new_name="discount_price",
        ),
    ]
