# Generated by Django 5.2.2 on 2025-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0003_rename_customer_category_discount_percent_order_discount_percent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="inward_date",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="cloth_description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="delivery_charge_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="delivery_description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="handling_description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="service_description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="vat_percent",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="vat_price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Planned delivery date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="inward_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the order was received.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
