# Generated by Django 5.2.2 on 2025-07-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_delivery_date_remove_order_inward_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="handling_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
