# Generated by Django 5.2.2 on 2025-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_handling_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="customer_category_name",
            field=models.CharField(max_length=50),
        ),
    ]
