# Generated by Django 5.2.2 on 2025-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderitem_customer_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_carpet",
            field=models.BooleanField(default=False),
        ),
    ]
