# Generated by Django 5.2.2 on 2025-07-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_is_carpet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("apply_rounding", models.BooleanField(default=False)),
                ("rating", models.CharField(blank=True, max_length=10, null=True)),
                ("rating_link", models.BooleanField(default=False)),
                (
                    "rounding_amount",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Amount received in this payment",
                        max_digits=12,
                    ),
                ),
                (
                    "change_return",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.0,
                        help_text="Change returned to the customer",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                            ("credit", "Credit"),
                            ("other", "Other"),
                        ],
                        help_text="Payment method (cash, card, credit, etc.)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this payment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
