# Generated by Django 5.2.2 on 2025-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="inward_date",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Planned delivery date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="inward_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the order was received.",
                null=True,
            ),
        ),
    ]
