# Generated by Django 5.2.2 on 2025-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_orderitem_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("wallet", "Wallet"),
                    ("repayment", "Repayment"),
                    ("credit", "Credit"),
                    ("other", "Other"),
                ],
                help_text="Payment method (cash, card, credit, etc.)",
                max_length=20,
            ),
        ),
    ]
