# Generated by Django 5.2.2 on 2025-09-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_orderpayment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="repayment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("wallet", "Wallet"),
                    ("credit", "Credit"),
                    ("other", "Other"),
                ],
                help_text="Repayment method (cash, card, credit, etc.)",
                max_length=20,
                null=True,
            ),
        ),
    ]
