# Generated by Django 5.2.2 on 2025-07-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customer_data_remove_customer_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customercategory",
            options={
                "verbose_name": "Customer Category",
                "verbose_name_plural": "Customer Categories",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
