# Generated by Django 5.2.2 on 2025-07-03 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customercategory_options_customer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Customer's email address.",
                max_length=255,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_number",
            field=models.CharField(
                blank=True,
                help_text="Tax Identification Number (TIN/VAT/etc.) for this customer.",
                max_length=50,
                null=True,
            ),
        ),
    ]
