# Generated by Django 5.2.2 on 2025-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_email_customer_tax_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="Maximum credit allowed for this customer.",
                max_digits=12,
            ),
        ),
    ]
