# Generated by Django 5.2.2 on 2025-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_credit_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0.0,
                help_text="Maximum credit allowed for this customer.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
