# Generated by Django 5.2.2 on 2025-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_customer_credit_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercategory",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
