# Generated by Django 5.2.2 on 2026-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_customercategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="opening_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0.0,
                help_text="Opening outstanding amount for this customer.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
