# Generated by Django 5.2.2 on 2025-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authuser",
            name="country_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="authuser",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
