# Generated by Django 5.2.2 on 2025-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authuser_address_authuser_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture for the user",
                null=True,
                upload_to="user_profiles/",
            ),
        ),
    ]
