# Generated by Django 5.2.2 on 2025-09-05 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_authuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this user record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authuser",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated this user record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this group detail record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupdetails_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupdetail",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who last updated this group detail record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupdetails_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
