# Generated by Django 5.2.2 on 2026-04-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0006_organization_created_by_organization_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=100, unique=True)),
                ("raw_key", models.TextField()),
                ("company_name", models.CharField(max_length=255)),
                ("plan_name", models.CharField(max_length=100)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("expires_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
