# Generated by Django 5.2.2 on 2026-08-28 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=100, unique=True)),
                (
                    "license_type",
                    models.CharField(
                        choices=[("activation", "Activation"), ("renewal", "Renewal")],
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("plan_name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("max_branches", models.PositiveIntegerField(default=1)),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("duration_days", models.PositiveIntegerField()),
                ("expires_on", models.DateField()),
                (
                    "admin_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("admin_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "admin_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "license_key",
                    models.CharField(blank=True, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
