# Generated by Django 5.2.2 on 2026-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="admin_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
