# Generated by Django 5.2.2 on 2026-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.TextField(blank=True, editable=False, unique=True),
        ),
    ]
