# Generated by Django 5.2.2 on 2026-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0003_alter_license_license_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(
                blank=True, editable=False, max_length=2048, unique=True
            ),
        ),
    ]
