# Generated by Django 5.2.2 on 2025-11-24 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0004_brandmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITGRP_MAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='0 = inactive, 1 = active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch / Division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_branches', to='organizations.organization')),
                ('brdcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_brands', to='purchase.brandmaster', verbose_name='Brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_created', to=settings.AUTH_USER_MODEL)),
                ('grpcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_groups', to='purchase.groupmaster', verbose_name='Group')),
                ('organization', models.ForeignKey(blank=True, help_text='Main organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_organizations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itgrp_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
