# Generated by Django 5.2.2 on 2025-11-24 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0006_unitmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itname', models.CharField(max_length=191)),
                ('itnamear', models.CharField(blank=True, max_length=191, null=True)),
                ('dubcost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('impcost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('itcost', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('rtrate', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('vatrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items_branch', to='organizations.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('group_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_groupmap', to='purchase.itgrp_map')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items_org', to='organizations.organization')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_supplier', to='purchase.suppliermaster')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_unit', to='purchase.unitmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_vat', to='purchase.vatmaster')),
            ],
        ),
    ]
