# Generated by Django 5.2.2 on 2025-11-26 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_country_tax_number_mask'),
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0010_inv_tran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACC_TRAN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrno', models.CharField(editable=False, max_length=80, unique=True)),
                ('serial_no', models.PositiveIntegerField(blank=True, default=None, editable=False, null=True)),
                ('voucher_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_ex_vat', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('amount_inc_vat', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('paymode', models.IntegerField(choices=[(0, 'NULL'), (1, 'Cash'), (2, 'Bank')], default=0)),
                ('paid_to', models.CharField(blank=True, max_length=191, null=True)),
                ('vatin', models.CharField(blank=True, max_length=50, null=True)),
                ('narration', models.CharField(blank=True, max_length=200, null=True)),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_branch', to='organizations.organization')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_country', to='master.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_org', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_updated', to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_vat', to='purchase.vatmaster')),
                ('vr_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions_vrtype', to='purchase.vrtypemaster')),
            ],
            options={
                'verbose_name': 'Account Transaction',
                'verbose_name_plural': 'Account Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
