# Generated by Django 5.2.2 on 2025-11-26 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0011_acc_tran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCT_MAST',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acno', models.PositiveIntegerField(editable=False, unique=True)),
                ('accname', models.CharField(max_length=200)),
                ('accname_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('grpcode', models.CharField(blank=True, choices=[('ASS', 'ASSET'), ('LIB', 'LIABILITY'), ('INC', 'INCOME'), ('EXP', 'EXPENSE')], max_length=10, null=True)),
                ('baltype', models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')])),
                ('actype', models.CharField(choices=[('G', 'General / Group'), ('D', 'Detail')], max_length=1)),
                ('acmapno', models.PositiveIntegerField(editable=False)),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('curbal', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acct_mast_branch', to='organizations.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acct_mast_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acct_mast_org', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acct_mast_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Master',
                'verbose_name_plural': 'Account Masters',
                'ordering': ['acno'],
            },
        ),
    ]
