# Generated by Django 5.2.2 on 2025-11-26 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0012_acct_mast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCT_MAST_MAP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acmapno', models.PositiveIntegerField(editable=False, unique=True)),
                ('totlev', models.PositiveIntegerField(default=1)),
                ('lev1', models.PositiveIntegerField(blank=True, null=True)),
                ('lev2', models.PositiveIntegerField(blank=True, null=True)),
                ('lev3', models.PositiveIntegerField(blank=True, null=True)),
                ('lev4', models.PositiveIntegerField(blank=True, null=True)),
                ('lev5', models.PositiveIntegerField(blank=True, null=True)),
                ('lev6', models.PositiveIntegerField(blank=True, null=True)),
                ('lev7', models.PositiveIntegerField(blank=True, null=True)),
                ('lev8', models.PositiveIntegerField(blank=True, null=True)),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctmastmap_branch', to='organizations.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctmastmap_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctmastmap_org', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acctmastmap_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Master Mapping',
                'verbose_name_plural': 'Account Master Mappings',
                'ordering': ['acmapno'],
            },
        ),
    ]
