# Generated by Django 5.2.2 on 2025-11-26 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0013_acct_mast_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACC_TRAN_DETA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_date', models.DateField(default=django.utils.timezone.localdate)),
                ('serial_no', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('dc_flag', models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')])),
                ('list_code_ac', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=18)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('accestat', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acc_tran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchase.acc_tran')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_account', to='purchase.acct_mast')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_branch', to='organizations.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_org', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_updated', to=settings.AUTH_USER_MODEL)),
                ('vr_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_tran_details_vrtype', to='purchase.vrtypemaster')),
            ],
            options={
                'verbose_name': 'Account Transaction Detail',
                'verbose_name_plural': 'Account Transaction Details',
                'ordering': ['acc_tran', 'serial_no'],
            },
        ),
    ]
