# Generated by Django 5.2.2 on 2025-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_acc_tran_deta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acc_tran',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='acc_tran_deta',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='acct_mast',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='acct_mast_map',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='brandmaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='groupmaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='inv_tran',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='itemmaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='itgrp_map',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='suppliermaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='unitmap',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='unitmaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vatmaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vrtypemaster',
            old_name='accestat',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='acc_tran',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
