# Generated by Django 5.2.2 on 2025-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_rename_accestat_acc_tran_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_tran',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acc_tran',
            name='paymode',
            field=models.CharField(choices=[('NULL', 'NULL'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='acc_tran_deta',
            name='dc_flag',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='acc_tran_deta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acct_mast',
            name='actype',
            field=models.CharField(choices=[('General / Group', 'General / Group'), ('Detail', 'Detail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='acct_mast',
            name='baltype',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='acct_mast',
            name='grpcode',
            field=models.CharField(blank=True, choices=[('ASSET', 'ASSET'), ('LIABILITY', 'LIABILITY'), ('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acct_mast',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acct_mast_map',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inv_tran',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itgrp_map',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unitmap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unitmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vatmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vrtypemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
