# Generated by Django 5.2.2 on 2025-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_created_by_organization_updated_by'),
        ('purchase', '0016_alter_acc_tran_is_active_alter_acc_tran_paymode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_tran',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='acc_tran_deta',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='acct_mast',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='acct_mast_map',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='brandmaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='groupmaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inv_tran',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itgrp_map',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='suppliermaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='unitmap',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='unitmaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vatmaster',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='vrtypemaster',
            name='branch',
        ),
        migrations.AddField(
            model_name='acc_tran',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='acc_transactions_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='acc_tran_deta',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='acc_tran_details_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='acct_mast',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='acct_mast_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='acct_mast_map',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='acctmastmap_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='brandmaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_brands_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='groupmaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_groups_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='inv_tran',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_inv_transactions_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_items_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='itgrp_map',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='itgrp_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='suppliers_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='unitmap',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='unitmap_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='unitmaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_units_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='vatmaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchase_vats_branches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='vrtypemaster',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='vrtype_branches', to='organizations.organization'),
        ),
    ]
