# Generated by Django 5.2.2 on 2026-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_purchaseinvoice_purchaseinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='vat_per',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paymode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
