# Generated by Django 5.2.2 on 2026-08-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_purchase_invoice_paymode_string_line_vat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='acct_mast',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='purchase.acct_mast'),
        ),
        migrations.AddField(
            model_name='acct_mast_map',
            name='acct_mast',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_map', to='purchase.acct_mast'),
        ),
    ]
