# Generated by Django 5.2.2 on 2026-08-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_add_vat_fields_vr_type_paid_to_narration_fix_payment_mode'),
        ('purchase', '0020_acct_mast_parent_acct_mast_map_acct_mast'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_gl_account', to='purchase.acct_mast'),
        ),
    ]
