# Generated by Django 5.2.2 on 2025-06-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organizations.organization",),
        ),
    ]
