# Generated by Django 5.2.2 on 2025-06-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="max_branches",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
