# Generated by Django 5.2.2 on 2025-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_plan_max_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="currency_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="service_vat_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
