# Generated by Django 5.2.2 on 2026-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_created_by_organization_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="vat_registration_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
