# Generated by Django 5.2.2 on 2026-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_plan_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
