# Generated by Django 5.2.2 on 2026-08-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_alter_plan_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
