# Generated by Django 5.2.2 on 2025-06-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_alter_plan_max_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Branches where this cloth type is available.",
                        related_name="branch_cloth_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main organization this cloth type belongs to. Optional if shared across branches.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_cloth_types",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cloth Type",
                "verbose_name_plural": "Cloth Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WashingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Branches where this washing type is available",
                        related_name="branch_washing_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main/root organization of the washing type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_washing_types",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Washing Type",
                "verbose_name_plural": "Washing Types",
            },
        ),
    ]
