# Generated by Django 5.2.2 on 2025-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_clothtype_created_by_clothtype_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothtype",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="washingtype",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
