# Generated by Django 5.2.2 on 2025-06-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_clothtype_is_pinned_washingtype_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothtype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="washingtype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
