# Generated by Django 5.2.2 on 2025-06-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0004_clothtype_price_washingtype_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothtype",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="washingtype",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
