# Generated by Django 5.2.2 on 2025-06-30 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_alter_clothtype_price_alter_washingtype_price"),
        ("organizations", "0003_alter_plan_max_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Branches where this delivery type is available",
                        related_name="branch_delivery_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_types_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main/root organization of the delivery type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_delivery_types",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_types_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Type",
                "verbose_name_plural": "Delivery Types",
            },
        ),
    ]
