# Generated by Django 5.2.2 on 2025-06-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0008_handlingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothtype",
            name="is_carpet",
            field=models.BooleanField(default=False),
        ),
    ]
