# Generated by Django 5.2.2 on 2025-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0009_clothtype_is_carpet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dial_code", models.CharField(max_length=10)),
                ("iso_code", models.CharField(max_length=3, unique=True)),
                ("flag_emoji", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
    ]
