# Generated by Django 5.2.2 on 2025-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0010_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverytype",
            name="price",
        ),
        migrations.AddField(
            model_name="deliverytype",
            name="charge_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
