# Generated by Django 5.2.2 on 2025-07-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0011_remove_deliverytype_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothtype",
            name="arabic_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
