# Generated by Django 5.2.2 on 2025-07-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0012_clothtype_arabic_name"),
        ("organizations", "0003_alter_plan_max_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("secondary_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_size_based_price", models.BooleanField(default=False)),
                ("is_laundry", models.BooleanField(default=False)),
                (
                    "laundry_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("is_pressing", models.BooleanField(default=False)),
                (
                    "pressing_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("is_dry_clean", models.BooleanField(default=False)),
                (
                    "dry_clean_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("is_steam", models.BooleanField(default=False)),
                (
                    "steam_price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image of the item",
                        null=True,
                        upload_to="item_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Branches where this item is available.",
                        related_name="branch_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main organization this item belongs to. Optional if shared across branches.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["name"],
            },
        ),
    ]
