# Generated by Django 5.2.2 on 2025-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0013_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="secondary_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
