# Generated by Django 5.2.2 on 2025-07-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0014_alter_item_secondary_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="company_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="currency_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="currency_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="currency_symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="is_main_currency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="language_code",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="language_name",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="luxury_tax_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="country",
            name="mobile_number_max_digits",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="country",
            name="service_vat_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
