# Generated by Django 5.2.2 on 2025-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0015_country_company_code_country_currency_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="company_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
