# Generated by Django 5.2.2 on 2025-10-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0016_alter_country_company_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="dry_clean_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_dry_clean",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_laundry",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_pressing",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_steam",
        ),
        migrations.RemoveField(
            model_name="item",
            name="laundry_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="pressing_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="steam_price",
        ),
        migrations.AddField(
            model_name="item",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Store extra details in JSON format (default = {})",
            ),
        ),
    ]
