# Generated by Django 5.2.2 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master",
            "0017_remove_item_dry_clean_price_remove_item_is_dry_clean_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="tax_number_mask",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
