# Generated by Django 5.2.2 on 2026-05-13 04:17

from django.db import migrations


def seed_whatsapp_number(apps, schema_editor):
    AppSettings = apps.get_model('master', 'AppSettings')
    AppSettings.objects.get_or_create(
        key='whatsapp_number',
        defaults={
            'value': '916379758027',
            'description': 'MSG91 integrated WhatsApp sender number',
        }
    )


def remove_whatsapp_number(apps, schema_editor):
    AppSettings = apps.get_model('master', 'AppSettings')
    AppSettings.objects.filter(key='whatsapp_number').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_add_appsettings_model'),
    ]

    operations = [
        migrations.RunPython(seed_whatsapp_number, remove_whatsapp_number),
    ]
