# Generated by Django 5.2.2 on 2026-09-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0021_seed_msg91_auth_key_and_namespace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("api_add_database_backup", "Can create database backups via API"),
                    ("api_view_database_backup", "Can view database backups via API"),
                    (
                        "api_restore_database_backup",
                        "Can restore database backups via API",
                    ),
                    (
                        "api_delete_database_backup",
                        "Can delete database backups via API",
                    ),
                ],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
